### ISSUE TITLE
Replace nodes

### ISSUE THREAD

**Issue by LandonAConway** [x2048/terraform#13]
I would like to see a feature where nodes get replaced if they are not air nodes. I have tried doing this before using the landslide too but it only replaces one layer of nodes.

**Comment by x2048** [comment]
If I understood you correctly, Mask field should allow you to replace nodes with other node type. You can set up more brushes for more replacement rules.


![Screenshot_20220424-182445_Firefox Focus.jpg](https://user-images.githubusercontent.com/4933697/164986335-f70e9379-5269-493e-bf1b-c4ece93ec0df.jpg)

**Comment by x2048** [comment]
@LandonAConway 

Here is a high-quality screenshot of the Paint and Mask fields that would replace "dirt with grass" with tree leaves:
![image](https://user-images.githubusercontent.com/4933697/167478724-5e8c6f32-7eec-47d9-8950-054f18ed4e9d.png)

The result looks like this:
![image](https://user-images.githubusercontent.com/4933697/167478826-779101b8-77cc-4fb4-a204-9fecd5d7e655.png)

Notice that the stone under the leaves is not replaced.

Is this the kind of functionality you were looking for?

**Comment by x2048** [comment]
I will now close the issue. Feel free to comment and reopen.

**Comment by LandonAConway** [comment]
> @LandonAConway
> 
> Here is a high-quality screenshot of the Paint and Mask fields that would replace "dirt with grass" with tree leaves: ![image](https://user-images.githubusercontent.com/4933697/167478724-5e8c6f32-7eec-47d9-8950-054f18ed4e9d.png)
> 
> The result looks like this: ![image](https://user-images.githubusercontent.com/4933697/167478826-779101b8-77cc-4fb4-a204-9fecd5d7e655.png)
> 
> Notice that the stone under the leaves is not replaced.
> 
> Is this the kind of functionality you were looking for?

Sorry for the late reply. No. I found an issue where replacing nodes with stone only replaced nodes if they were under air.

**Comment by x2048** [comment]
@LandonAConway  This is controlled by `Surface` flag on the left-hand side. Make sure it is unchecked to replace all nodes in range.
