### ISSUE TITLE
Tools not working with fast_move on Android

### ISSUE THREAD

**Issue by depascalis** [x2048/terraform#14]
Tools (brush and light) are not working when `fast_move` is enabled and active on Android. I have verified this on three different Androids. Unfortunately I can't find any relative log messages.
If you don't have an Android, just ping me if you need any assistance with testing etc and I'll see if I can help.

**Comment by x2048** [comment]
OK, so on Android (and any touch UI), Minetest engine force-presses Aux1 ('E') for you when fast is enabled. And in Terraform Aux1 is tied to Undo operation for any tool. I can add a chat command to toggle the behavior for a player. Would that work?

**Comment by depascalis** [comment]
Oh cool, I didn't know that, I use the undo-tool for that. It will definitely work for me as it wouldn't change my current flow. Thank you ♥️
